### ISSUE TITLE
Idea : Get rid of Point submodule

### ISSUE THREAD

**Issue by Chadtech** [Elm-Canvas/elm-canvas#60]
We made the point submodule because some times you want to specify stuff in terms of `Float` and get anti aliased edges, and other times you want things to be really exact about each pixel so you should use `Int`. I think this was kind of over engineered, and it doesnt fully address the concern, for example a canvas that is 199 pixels wide _internally_, and 200 pixels wide _externally_ will be anti aliased no matter what.

I propose switching from `Point -> ...` typing to `Float -> Float -> ...` typing. The pixel perfect question can be handled else where.

**Comment by mrozbarry** [comment]
I think this is a pretty sane approach, especially because there is no core library currently that implements a graphical point type.
