### ISSUE TITLE
Using v1.0.0, import Canvas exposing (Size) fails.

### ISSUE THREAD

**Issue by mrozbarry** [Elm-Canvas/elm-canvas#9]
I'm using elm-git-install, and my dependency set to: `"elm-community/canvas": "1.0.0 <= v < 2.0.0"`. In master, I see `Size` being exposed in Canvas.elm, but locally in my elm-stuff/packages directory, Size is not being exposed properly. I'm not sure if for some reason I have the wrong version number (which seems contrary to you elm-package.json file), or if elm-git-install is backing onto the elm package website and there is a sync issue, or if for some reason elm-git-install is pointing at the wrong ref in your repo.

**Comment by mrozbarry** [comment]
It seems that your 1.0.0 tag doesn't expose `Size`.

**Comment by Chadtech** [comment]
Hey Mrozbarry,

Thanks! I just fixed it. The problem was I pushed to 1.0.0, updated the API to include `Size`, but then didnt push that into the tag 1.0.0. Right now the name 1.0.0 really doesnt mean much.
